parameters:

services:
  _defaults:
    public: false
  #CONTROLLERS
  GabrielCorrea\WebpayBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']
  gabriel_correa.webpay_service:
    class: GabrielCorrea\WebpayBundle\Service\WebpayService
    arguments:
      - "@twig"
      - "@gabriel_correa_webpay_save_transaction_handler"
    public: true

  GabrielCorrea\WebpayBundle\Service\WebpayService: '@gabriel_correa.webpay_service'




