parameters:
#  mindbody_source_name: '%env(MINDBODY_SOURCE_NAME)%'
#  mindbody_source_password: '%env(MINDBODY_SOURCE_PASSWORD)%'
#  mindbody_admin_user: '%env(MINDBODY_ADMIN_USER)%'
#  mindbody_admin_password: '%env(MINDBODY_ADMIN_PASSWORD)%'
#  mindbody_site_ids: '%env(json:MINDBODY_SITE_IDS)%'
#  router.request_context.host: '%env(HOST)%'
#  router.request_context.scheme: https
#  router.request_context.base_url: ''
  webpay_final_url: '%env(GABRIELCORREA_WEBPAY_BUNDLE_FINAL_URL)%'
  webpay_path_key: '%env(GABRIELCORREA_WEBPAY_BUNDLE_PATH_KEY)%'
  webpay_path_crt:  '%env(GABRIELCORREA_WEBPAY_BUNDLE_PATH_CRT)%'
  webpay_is_dev_end: '%env(GABRIELCORREA_WEBPAY_BUNDLE_IS_DEV_END)%'

services:
  _defaults:
    public: false
  #CONTROLLERS
  GabrielCorrea\WebpayBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']
  #SERVICES
  #file_cache_service:
#    class: Symfony\Component\Cache\Simple\FilesystemCache
#  miguel_alcaino.mb_api:
#    class: MiguelAlcaino\MindbodyPaymentsBundle\Service\MB_API
#    arguments:
#      $sourceName: '%mindbody_source_name%'
#      $password: '%mindbody_source_password%'
#      $siteIds: '%mindbody_site%'
  gabriel_correa.webpay_service:
    class: GabrielCorrea\WebpayBundle\Service\WebpayService
    arguments:
      - "@twig"
      - "@gabriel_correa_webpay_save_transaction_handler"
    public: true

  GabrielCorrea\WebpayBundle\Service\WebpayService: '@gabriel_correa.webpay_service'




